baseurl = "https://sivid.github.io/"
languageCode = "en-us"
title = "my (new) blog"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[Params]
  Author = "sivid"
  googleAnalytics = "UA-81820759-1"
  GoogleAnalyticsUserID = "UA-81820759-1"